instill-ai/model-backend

- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
Because
- we'd like to track issues and PRs in the [VDP](https://github.com/orgs/instill-ai/projects/5) project.
This commit
- add Github Actions to add issues and PRs to the VDP project according to [automating the project (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/managing-the-visibility-of-your-projects)
> ci: add issue and pr to VDP project

- Dockerfile
- README.md
- configs/config.yaml
- docker-compose.yml
- examples-go/grpc_client.go
- go.mod
- go.sum
- internal/constants.go
- internal/db/migrations/000001_init.up.sql
- internal/db/migrations/000002_add_cv_task.down.sql
- internal/db/migrations/000002_add_cv_task.up.sql
- internal/db/migrations/000003_add_triton_model_table.down.sql
- internal/db/migrations/000003_add_triton_model_table.up.sql
- pkg/models/model.go
- pkg/repository/model.go
- pkg/services/model.go
- rpc/model.go
- tests/create_model_test.go
Because
- user wants to specify model name when they create a model and auto increase model version
This commit
- support model name and model version in CreateModel method (mapping model folder into Triton server based on namespace, model name, folder model, and model version)
- close #20
- close #21 
- close #22
> feat: support model name when creating model

- pkg/services/model.go
Because
- versions mismatch between model package (ensemble by preprocessing -> inference -> post-processing) and triton model repository
This commit
- fix Triton model version when making inference
> fix: correct version when making inference

- rpc/model.go
Because
- should delete uploaded zip file model to save disk
This commit
- delete the uploaded zip file
> chore: delete the uploaded zip file

- internal/db/migration/000001_init.up.sql
- pkg/datamodel/datamodel.go
- pkg/handler/handler.go
- pkg/handler/metadata.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- Soft delete support
This commit
- Update datamodel for soft delete
> chore: update soft delete in repository

- integration-test/grpc.js
- integration-test/rest.js
- pkg/handler/handler.go
- pkg/service/service.go
Because
- Support update description for the model
This commit
- Add update model method
> chore: add updatemodel handler

- pkg/handler/mock_service_test.go
- pkg/repository/repository.go
- pkg/service/mock_repository_test.go
- pkg/service/service_test.go
Because
- Update unit test after refactoring code
This commit
- Update unit test for service layer
> chore: update unittest in service layer

- cmd/init/main.go
- integration-test/rest.js
- pkg/repository/repository.go
Because
- Get list API return response depends on view setup
This commit
- Update get list model definition, model, and model instance
- Fix a bug related to init model definition
> chore: update view for get list api

- cmd/main/interceptor.go
- cmd/main/middleware.go
- integration-test/grpc_create_model.js
- integration-test/grpc_deploy_model.js
- integration-test/grpc_infer_model.js
- integration-test/grpc_publish_model.js
- integration-test/grpc_query_model.js
- integration-test/grpc_query_model_instance.js
- integration-test/grpc_update_model.js
- integration-test/rest_create_model.js
- integration-test/rest_deploy_model.js
- integration-test/rest_infer_model.js
- integration-test/rest_publish_model.js
- integration-test/rest_query_model.js
- integration-test/rest_query_model_instance.js
- integration-test/rest_update_model.js
- internal/util/util_test.go
- pkg/handler/handler.go
- pkg/handler/metadata.go
Because
- Update test dummy model repository
This commit
- Change test dummy model repository to Instill organization's repository
> chore: update test github repo

- pkg/datamodel/datamodel.go
- pkg/handler/convert.go
- pkg/handler/handler.go
Because
- Missing configuration output of local model
This commit
- Add local model configuration output
> chore: fix output of local model configuration

- config/config.go
- config/config.yaml
- pkg/handler/convert.go
- pkg/handler/handler.go
- pkg/handler/metadata.go
Because
- User id could be changed then should store user permalink `users/{uid}` in database
This commit
- Store user permalink instead of user id
> chore: store user permalink instead of username

- docker-compose.yml
- internal/db/migration/000001_init.up.sql
- pkg/datamodel/datamodel.go
- pkg/handler/convert.go
- pkg/handler/handler.go
- pkg/handler/metadata.go
- pkg/handler/mock_service_test.go
- pkg/repository/repository.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
- pkg/service/service_test.go
Because
- The permalink will use for all cross reference
This commit
- Update model definition to permalink instead of name
> chore: update model definition reference to uid instead of name

- docker-compose.yml
- pkg/datamodel/credential.go
- pkg/handler/handler.go
- pkg/handler/mock_service_test.go
- pkg/repository/repository.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
- pkg/usage/usage.go
Because
- missing updating model definitions and tasks in usage collection
This commit
- add model definitions and tasks in usage collection
- remove usage service in docker compose
> fix: update model definitions and tasks in usage collection

- config/init/instill/seed/model_definitions.yaml
- integration-test/grpc_query_model_definition.js
- integration-test/rest_query_model_definition.js
- internal/util/util.go
- pkg/datamodel/datamodel.go
- pkg/handler/convert.go
- pkg/handler/handler.go
Because
- Beside GitHub model-backend also support cloud model storage with ArtiVC
This commit
- Add create a model on gcloud using ArtiVC
> feat: support artivc

- cmd/main/main.go
- go.mod
- go.sum
- integration-test/rest_infer_model.js
- pkg/handler/handler.go
Because
- stream trigger model instance method for using in pipeline-backend
This commit
- add stream trigger model instance method
> chore: add stream trigger model instance method

- config/config.go
- config/config.yaml
- internal/external/external.go
Because
- update usage collection
This commit
- update function InitUsageServiceClient
> chore: update usage collection

- pkg/service/service.go
Because
- return error 500 when have internal error from triton server for deploying model 
This commit
- close #110
> fix: status code when deploy model error

- Dockerfile
- Dockerfile.dev
- assets/huggingface-vit-template/README.md
- assets/huggingface-vit-template/huggingface-infer/config.pbtxt
- assets/huggingface-vit-template/huggingface-infer/imagenet_labels.txt
- assets/huggingface-vit-template/huggingface/1/git_info.txt
- assets/huggingface-vit-template/huggingface/config.pbtxt
- assets/huggingface-vit-template/pre/1/git_info.txt
- assets/huggingface-vit-template/pre/1/model.py
- assets/huggingface-vit-template/pre/config.pbtxt
- config/init/instill/seed/model_definitions.yaml
- internal/util/util.go
- pkg/datamodel/datamodel.go
- pkg/handler/handler.go
- pkg/service/service.go
Because
-  support creating a classification model from HuggingFace repository
This commit
- add HuggingFace model definition and HuggingFace model creation
> feat: support creating a HuggingFace model

- cmd/main/main.go
- integration-test/rest_infer_model.js
- internal/util/const.go
- pkg/handler/handler.go
- pkg/service/service.go
Because
- wrong model definition in list model method
- missing zero value in the output
This commit
- fix model definition in output
- fix missing zero value in the output
- close #116 
- close #117
> fix: model definition in list model and missing zero in output

- assets/huggingface-vit-template/huggingface-infer/config.pbtxt
- assets/scripts/query_model_onnx.py
- config/config.yaml
- config/init/instill/seed/model_definitions.yaml
- go.mod
- go.sum
- integration-test/rest_query_model_instance.js
- internal/resource/resource.go
- internal/util/util.go
- pkg/handler/handler.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- support label output for huggingface model
This commit
- add label file by reading from config.json in huggingface model
> chore: update label for huggingface model

- cmd/init/util.go
- config/init/instill/seed/model_definitions.yaml
- config/model/model.json
- config/model/model_instance.json
- config/model/model_instance_card.json
- go.mod
- go.sum
- integration-test/grpc_create_model.js
- integration-test/proto/model.proto
- integration-test/rest_create_model.js
- integration-test/rest_query_model.js
- integration-test/rest_query_model_instance.js
- pkg/datamodel/jsonschema.go
- pkg/handler/convert.go
- pkg/handler/handler.go
Because
- model configuration should be in JSON format instead of string ([refer](https://github.com/instill-ai/protobufs/issues/85))
This commit
- update model configuration into JSON format
> chore: update configuration to json object

- cmd/main/main.go
- cmd/main/misc.go
- config/config.go
- config/config.yaml
- config/init/instill/seed/model_definitions.yaml
- go.mod
- go.sum
- internal/external/external.go
- pkg/datamodel/datamodel.go
- pkg/handler/convert.go
- pkg/handler/handler.go
- pkg/service/service.go
- pkg/service/service_test.go
Because
- change status error code
This commit
- close #127
- close #126
> chore: update status 422 when delete in use model

- cmd/main/main.go
- go.mod
- go.sum
- integration-test/rest.js
- integration-test/rest_create_model.js
- integration-test/rest_infer_model.js
- pkg/handler/convert.go
- pkg/handler/handler.go
- pkg/handler/mock_service_test.go
- pkg/service/service.go
Because
- refactor format of task output
This commit
- update task output format corresponding with the new protobuf message
> chore: update new format of output task

- cmd/init/convert.go
- cmd/init/db.go
- cmd/init/main.go
- cmd/init/util.go
- config/init/instill/seed/model_definitions.yaml
- config/model/model_definition.json
- integration-test/rest_infer_model.js
- integration-test/rest_query_model_definition.js
- internal/db/migration/000001_init.up.sql
- pkg/datamodel/datamodel.go
- pkg/datamodel/jsonschema.go
- pkg/handler/handler.go
Because
- support release stage for model definitions
This commit
- add release stage for model definitions
- close #146
> feat: add release stage for model definition

- go.mod
- go.sum
- pkg/service/service.go
Because
- unify inference output for detection, keypoint and OCR model
This commit
-  update inference output format
> chore: update protobuf with new inference output format

- integration-test/rest_create_model.js
- integration-test/rest_infer_model.js
Because
- change in inference output protobuf
This commit
- update the integration-test with the updated protobuf
> chore: update integration test

- go.mod
- go.sum
- internal/triton/const.go
- internal/triton/triton.go
- pkg/service/service.go
Because
- OCR output should have a confidence score like other models
This commit
- add confidence score for OCR output
- update output format following the latest protobuf
> feat: add confidence score for ocr output

- integration-test/rest_infer_model.js
Because
- the inference output format change
This commit
- update integration-test with the new inference output format
> chore: update integration-test with new output format

- Dockerfile
- Dockerfile.dev
Because
-  updated python libraries cause expected issues
This commit
- fix python libraries including transformer, torch and onnx version
> chore: fix python libraries

- cmd/main/main.go
- go.mod
- go.sum
- integration-test/grpc_deploy_model.js
- integration-test/grpc_infer_model.js
- integration-test/grpc_publish_model.js
- integration-test/grpc_query_model.js
- integration-test/grpc_query_model_instance.js
- integration-test/grpc_update_model.js
- integration-test/proto/model_service.proto
- integration-test/rest.js
- integration-test/rest_create_model.js
- integration-test/rest_deploy_model.js
- integration-test/rest_infer_model.js
- integration-test/rest_model_card.js
- integration-test/rest_publish_model.js
- integration-test/rest_query_model.js
- integration-test/rest_query_model_instance.js
- integration-test/rest_update_model.js
Because
- Krakend reserve character `: used in api-gateway so endpoint could not contain that character
This commit
- change character `:` to `/`
> refactor: update endpoint compatible with krakend

- .pre-commit-config.yaml
- config/config.yaml
- go.mod
- go.sum
- internal/util/util.go
- pkg/service/service.go
- pkg/usage/usage.go
Because
- CORS configuration is set in docker-compose files
- triggering usage metric is not for only image
This commit
- remove cors default config
- rename usage metric
- upgrade pre-commit hooks
- fix go lint SA1024
> chore: change config and usage metric

- pkg/handler/handler.go
Because
- have a panic error in deploy/undeploy a model
This commit
- fix error using nil object
> fix: panic error with nil object

- go.mod
- go.sum
- internal/util/const.go
- pkg/handler/handler.go
Because
- get and list support `view` option
This commit
- add `view` option in get list operation method
> chore: update view operation

- integration-test/rest_create_model.js
Because
- update creating a model asynchronous
This commit
- update integration test
> chore: fix integration test

- go.mod
- go.sum
Because
-  update go dependencies
This commit
-  update go sum
> chore: update go sum

- cmd/worker/main.go
- go.sum
- internal/worker/model.go
- internal/worker/worker.go
- pkg/service/worker.go
Because
- list long-run operation is buggy 
This commit
- rename the add search attribute function
- update model UID and model instance UID to follow the format
> fix: fix list long-run operation error

- integration-test/rest_create_model.js
- pkg/handler/handler.go
Because
- reduce internet connection during integration test
This commit
- create a dummy GitHub info instead of calling to GitHub API
> chore: fix dummy model

- Dockerfile
- Dockerfile.dev
- Makefile
Because
- for security best practice, we should not use root for containers
This commit
- adopt non-root user and group in containers
> ci: adopt non-root user in container

- cmd/worker/main.go
Because
- adding search attributes in the model-backend using DinD is not good practice.
This commit
- move adding the search attributes into `temporal_admin_tools` container
> chore: remove adding search attributes in model worker initialization

- Dockerfile
- Dockerfile.dev
- Makefile
- internal/worker/worker.go
Because
- codebase requires regular housecleaning 
This commit
- tinkers
> ci: tinker codebase

- go.mod
- go.sum
- internal/util/const.go
- pkg/handler/handler.go
- pkg/handler/payload.go
Because
- the protobuf is updated
This commit
-  update the protobuf with a new task text generation and update the input of text to image task
- fix text to image input parser
> chore: update the latest protobuf

- assets/huggingface-vit-template/pre/1/model.py
Because
- update the Triton server to version 22.12
This commit
- update import Tensor with the Triton server change
> chore: update import for HuggingFace template model

- go.mod
- go.sum
Because
- usage service update
This commit
- update the updated usage service
> chore: update usage version

- Dockerfile
Because
- need change folder permission
This commit
- change folder permission before changing the container user
> chore: change folder permission before setting user for container

- internal/util/file.go
Because
- check ensemble model
This commit
- check the backend python also
> chore: check backend python for ensemble model

- internal/util/file.go
Because
- wrong subfolder creation code
This commit
- create subfolder in model-repository
> fix: fix subfolder creation

- internal/util/file.go
Because
- variable name same as the package name
This commit
- fix variable name
> fix: fix variable name

- pkg/service/service.go
Because
-  unify task input in protobuf
This commit
- update task input for test multipart trigger
> chore: update payload parser

- internal/triton/triton.go
- pkg/handler/handler.go
- pkg/handler/payload.go
Because
- change `vision` name to `image` for more specific
This commit
- update the variable name
> chore: update variable name

- go.sum
- integration-test/rest_query_model.js
- integration-test/rest_query_model_instance.js
- pkg/repository/repository.go
Because
- there is a bug in the pagination API including list models, model instances
This commit
- fix the bug when pagination
> fix: list models and model instances pagination

- pkg/handler/convert.go
Because
- missing tag in ArtiVC model output
This commit
- add tag in the model
> chore: add tag in model artivc output

- .github/workflows/integration-test.yml
Because
- adopt new vdp integration-test workflow component name change
This commit
- update workflow component name
> ci(action): update workflow component name to be align with vdp

- integration-test/rest.js
Because
- wrong logic in the rest integration test
This commit
- fix the rest integration test
> chore: fix rest integration test

- Dockerfile
- cmd/model/main.go
- config/model/model.json
- config/model/model_definition.json
- internal/resource/resource.go
- pkg/datamodel/jsonschema.go
- pkg/handler/private_handler.go
- pkg/handler/public_handler.go
- pkg/repository/repository.go
- pkg/service/service.go
- pkg/service/service_test.go
- pkg/util/file.go
- pkg/worker/model.go
Because
- initialize GitHub models when launching VDP
This commit
- add model initialization module
- fix some model instance name to model
> feat: add model initialization module

- cmd/model/main.go
Because
- deploy model take a long time
This commit
- increase deploy model timeout
> chore: increase timeout when deploy the model into 150min and add sleep

- cmd/model/main.go
- config/config.go
- config/config.yaml
Because
- support initializing Instill model hub when launching the VDP
This commit
- add model initialization configuration
> chore: add model initialization configuration

- integration-test/grpc_query_model_private.js
- integration-test/rest_query_model_private.js
Because
- some tests are out of date due to refactoring long-running operations
This commit
- update tests
> test: fix tests

- cmd/model/main.go
- pkg/repository/repository.go
Because
-support basic model's permission (list model could query user's own models and public models)
This commit
- update the list model in the repository to query public models
- INS-462
> chore: update visibility of models in the model hub

- pkg/worker/model.go
Because
- avoid latency of etcd resource state not reflecting current state when longrunning operation is done
This commit
- update etcd state through controller directly after operation is done
> chore(controller): set controller state when workflow is done

- cmd/model/main.go
Because
- when rerun model-init, the model-init could re-deploy existed model
This commit
- update model-init to re-deploy existed models
> chore: update model init to deploy existed models

- pkg/logger/logger.go
Because
- disable log for testing
This commit
- enable log after testing
> chore: enable logging

- cmd/model/main.go
Because
- add log to check the progress of model initialization
This commit
- add log
> chore: add log to model init module

- cmd/model/main.go
Because
- check model initialization progress
This commit
- add logs in model initialization
> chore: add log in model init module

- cmd/model/main.go
Because
- there is a segmentation error in log
This commit
- fix the log
> chore: fix log

- pkg/logger/logger.go
Because
- update the logger for easy tracing
This commit
- update the logger
> chore: update logging

- pkg/logger/logger.go
Because
- change logger level in production
This commit
- update logger
> chore: update logger

- cmd/main/main.go
Because
- usg will not retry to start if usage server down
This commit
- add retry for `usg.StartReporter()`
> chore: add retry for usg.StartReporter()

- go.mod
- go.sum
- integration-test/proto/vdp/pipeline/v1alpha/pipeline.proto
- integration-test/proto/vdp/pipeline/v1alpha/pipeline_private_service.proto
- integration-test/proto/vdp/pipeline/v1alpha/pipeline_public_service.proto
- pkg/service/service.go
Because
- we update new pipeline recipe format to support DAG
This commit
- adjust relevant code to support new recipe format
> chore: adopt new pipeline recipe format

- pkg/worker/model.go
Because
- fail integration-test when importing same model under itmode
This commit
- skip predeploy model check under itmode
> chore: fix uuid error in itmode

- .github/workflows/integration-test.yml
- Makefile
- cmd/main/main.go
- config/config.go
- config/config.yaml
- pkg/external/external.go
- pkg/handler/public_handler.go
- pkg/worker/model.go
Because
- retire `ITMODE` and change to `ITMODE_ENABLED` in VDP
This commit
- update `ITMODE` naming
Fixes INS-863
> chore(env): update vdp `ITMODE` naming

- cmd/main/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
Because
- leave cors to api-gateway
This commit
- remove cors
> chore: remove cors settings

- pkg/handler/public_handler.go
- pkg/middleware/interceptor.go
Because
- enforce authentication on non ce version
This commit
- update header injection
> chore: update header injection

- go.mod
- go.sum
- integration-test/grpc.js
- integration-test/grpc_create_model.js
- integration-test/grpc_query_model.js
- integration-test/proto/model/model/v1alpha/model.proto
- integration-test/proto/model/model/v1alpha/model_public_service.proto
- integration-test/rest_create_model_with_jwt.js
- integration-test/rest_query_model.js
- integration-test/rest_query_model_with_jwt.js
- internal/resource/resource.go
- pkg/handler/fieldannotation.go
- pkg/handler/private_handler.go
- pkg/handler/public_handler.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
- pkg/service/service_test.go
- pkg/service/worker.go
- pkg/utils/utils.go
- pkg/worker/model.go
Because
- pollute different datamodel usage with different scope
This commit
- refine datamodel definition and usage scope
> chore: refine datamodel scope

- pkg/handler/public_handler.go
- pkg/service/service.go
Because
- fail to validate local model configuration schema due to using wrong configuration type
This commit
- fix validation flow by using local model config json schema
> chore: fix create model stream method

- .github/workflows/integration-test.yml
- Makefile
- integration-test/const.js
Because
- consolidate api-gateways into one
This commit
- update api-gateway host in integration-test
> test: update api-gateway host

- cmd/model/main.go
- pkg/middleware/misc.go
Because
- cause `unauthenticated` without jwt header
This commit
- add jwt header injection in `init-model` script
> refactor(main): add jwt header injection

- pkg/triton/triton.go
Made the required upper and lower bound checks for required parameters for type conversions.
- For handling incorrect type exceptions.
This commit
- will help in checking upper and lower bounds when converting one type into another.
> chore(triton): update triton.go with bound checks

- Dockerfile
- Dockerfile.dev
- pkg/ray/ray.go
Because
- model healthcheck probe will cause replica scaling up
This commit
- probe ray serve instead of model application itself
> fix(ray): fix model healthcheck causing scaling loop

- Dockerfile
- Dockerfile.dev
- pkg/ray/ray.go
Because
- model weight file extension is fixed
This commit
- shift model file name into the actual model code
Fixes INS-2583
> fix(ray): fix model file extension

- pkg/ray/ray.go
Because
- account for cloud environment
This commit
- add ray addr to python arg
> chore(ray): add ray addr to python arg

- integration-test/proto/model/model/v1alpha/model.proto
Because
- the protobufs version of healthcheck is wrong
This commit
- fix protobufs version in proto file
> chore(deps): fix protobufs version in proto file

- integration-test/rest_infer_model.js
- pkg/ray/postprocess.go
- pkg/ray/ray.go
- pkg/service/service.go
- pkg/triton/const.go
- pkg/triton/postprocess.go
- pkg/triton/triton.go
Because
- gRPC default message size is 4MB which would exceed the SDXL model message size
This commit
- configure the gRPC message size based on configuration file (which is 20 MB now)
> fix(model): fix grpc message size limit issue

- config/config.go
- config/config.yaml
- pkg/handler/public_handler.go
- pkg/ray/ray.go
- pkg/utils/utils.go
Because
- avoid rate-limit for unauthenticated requests
This commit
- add optional config for github PAT
> feat(service): support basic github pat to avoid rate-limit

- pkg/utils/file.go
Because
- cached model file copying takes extensive time, implement progress writer to provide clearer view of the progress
This commit
- implement progress writer for model files copying
> chore(file): implement progress writer

- cmd/model/main.go
Because
- manually deleting pvc and db is not ideal
- redeploy unmatched model tag only
This commit
-  redeploy unmatched repo or tag only
resolves ins-1210
> refactor(model): redeploy unmatched repo or tag

- pkg/handler/payload.go
Because
- form data keys does not match protobuf definitions
This commit
- fix wrong form data key
> fix(payload): fix wrong form data key

- cmd/model/main.go
- integration-test/rest_query_model.js
- integration-test/rest_query_model_private.js
- pkg/handler/create.go
- pkg/handler/private.go
- pkg/handler/public.go
- pkg/middleware/misc.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/service.go
- pkg/service/worker.go
Because
- org model has wrong namespace and model repo path
This commit
- fix predeploy model namespace
- fix org model repo path
- fix `listModels` visibility
resolves INS-3623
> fix(pkg): fix org model namespace

- config/init/instill/seed/model_definitions.yaml
- pkg/datamodel/datamodel.go
- pkg/ray/ray.go
- pkg/worker/model.go
Because
- When deploying CPU model will result in `Error: setting up CDI devices: unresolvable CDI devices nvidia.com/gpu=all`
This commit
- add `gpu` flag in model configuration for Nvidia CDI setup
> fix(ray): check CDI availability for model container

- integration-test/grpc.js
- pkg/datamodel/datamodel.go
- pkg/datamodel/jsonschema.go
- pkg/db/migration/000005_init.up.sql
- pkg/handler/mock_service_test.go
- pkg/handler/public.go
- pkg/handler/stream.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
- pkg/utils/utils.go
- pkg/worker/utils.go
- pkg/worker/workflow.go
Because
- Model page will need to show detail prediction results for each trigger
This commit
- implement prediction records
resolves INS-4274
resolves INS-4276
> feat(prediction): implement sync/async prediction records

- .gitignore
- config/model/model.json
- pkg/ray/ray.go
Because
- Current spec schema blocks custom resource
This commit
- allow creating model with custom resource tag in local cluster
> chore(spec): fix wrong hardware schema

- pkg/datamodel/jsonschema.go
- pkg/handler/public.go
Because
- Hardware struct is not updated
This commit
- fix hardware struct
> chore(spec): fix hardware struct

- config/model/model.json
- pkg/datamodel/jsonschema.go
- pkg/handler/public.go
Because
- add `CPU` `GPU` and `Custom` to local cluster supported hardware list
This commit
- add `CPU` `GPU` and `Custom` to local cluster supported hardware list
> chore(spec): update hardware list

- config/init/instill/seed/model_definitions.json
- config/model/model.json
Because
- Update model spec schema for FE UI
This commit
- Update model spec schema for FE UI
> chore(config): update schema

- cmd/model/main.go
Because
- Model hub list format has to include `region` and `hardware`
This commit
- update model-hub model config struct
> chore(model): update init model config struct

- pkg/db/db.go
- pkg/repository/repository.go
Because
- Db replica config is missing
This commit
- fix missing replica plugin
> chore(db): fix missing replica plugin

- go.mod
- go.sum
- pkg/service/convert.go
- pkg/service/service.go
Because
- Allow query user to know what operation can be performed on the queried model
This commit
- add permission field in model object
> feat(model): add permission field in model object

- pkg/repository/repository.go
- pkg/service/service.go
Because
- List models endpoint return wrong list of models
This commit
- fix listModels acl check
> chore(acl): fix list acl check

- go.mod
- go.sum
- pkg/handler/operation.go
- pkg/handler/trigger.go
- pkg/service/service.go
- pkg/service/worker.go
- pkg/worker/workflow.go
Because
- Model overview page needs to retrieve input and output data from latest model async trigger
This commit
- implement methods to get latest model operation with embedded request and response
> feat(handler): implement get latest operation

- cmd/model/main.go
Because
- Wrongly reuse of context variable
This commit
- fix context variable
> chore(model): fix context variable

- cmd/main/main.go
Because
- Response size is limited
This commit
- add missing message size option
> fix(server): add missing message size option

- config/config.yaml
- go.mod
- go.sum
- pkg/datamodel/datamodel.go
- pkg/db/migration/000006_init.down.sql
- pkg/db/migration/000006_init.up.sql
- pkg/handler/private.go
- pkg/handler/public.go
- pkg/repository/errors.go
- pkg/repository/repository.go
- pkg/repository/transpiler.go
- pkg/service/convert.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
Because
- We are going to introduce model tag system. currently only support `featured` tag
This commit
- support featured tag for model resource
- include owner in model prop with `VIEW_BASIC`
resolves INS-4949
> feat(model): support model tag

- .github/workflows/integration-test.yml
Because
- Test models cannot be deployed
This commit
- fix test model image tags
> ci(workflows): fix test model image tag

- pkg/ray/ray.go
- pkg/service/service.go
Because
- Current `Starting` state consist phase that belongs to `Scaling` state
This commit
- set clear boundary between model state
> refactor(ray): set clear boundary between model state

- .github/workflows/integration-test.yml
- cmd/init/main.go
- cmd/main/main.go
- cmd/model/main.go
- cmd/worker/main.go
- pkg/datamodel/datamodel.go
- pkg/external/external.go
- pkg/handler/create.go
- pkg/handler/handler.go
- pkg/handler/operation.go
- pkg/handler/payload.go
- pkg/handler/private.go
- pkg/handler/public.go
- pkg/handler/stream.go
- pkg/handler/trigger.go
- pkg/handler/utils.go
- pkg/init/load.go
- pkg/init/util.go
- pkg/middleware/misc.go
- pkg/ray/postprocess.go
- pkg/ray/preprocess.go
- pkg/ray/ray.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/service.go
- pkg/service/worker.go
- pkg/usage/usage.go
- pkg/utils/const.go
- pkg/utils/utils.go
- pkg/worker/workflow.go
Because
- We are going to have separate codebase for different version of backend
This commit
- allow different scaling config under different environment
> refactor(ray): setup default scaling config for Core

- go.mod
- go.sum
- pkg/handler/mock_service_test.go
- pkg/handler/private.go
- pkg/handler/public.go
- pkg/repository/repository.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
Because
- We are going to support model image deletion
This commit
- implement user/org model image deletion
- refactor internal deploy/undeploy flow
> feat(model): support model version deletion

- pkg/handler/private.go
- pkg/ray/const.go
- pkg/ray/ray.go
- pkg/service/service.go
- pkg/worker/mock_ray_test.go
Because
- When ray restart for any reason, applications wont be brought back
This commit
- sync deployment configs when starting up
> feat(ray): sync deployment configs when starting up

- cmd/worker/main.go
- pkg/service/service.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- Usage collection spec hasn't been pinned down
This commit
- remove usage check/collect temporary
- remove excessive call to db
> chore(usage): disable usage

- pkg/worker/worker_test.go
Because
- need to make sure my changes does not break the functionalities
This commit
- added tests for trigger model activity
> fix(worker): added tests for trigger model activity

- .pre-commit-config.yaml
- cmd/main/main.go
- go.mod
- go.sum
- pkg/handler/create.go
- pkg/handler/operation.go
- pkg/handler/private.go
- pkg/handler/public.go
- pkg/handler/stream.go
- pkg/handler/trigger.go
- pkg/middleware/middleware.go
- pkg/repository/repository.go
- pkg/repository/utils.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
- pkg/service/utils.go
- pkg/service/worker.go
Because
- We'd like to simplify the API endpoints by merging users and organization endpoints into namespace endpoints.
This commit
- Introduces new namespace endpoints.
> feat(model): implement namespace endpoints

- cmd/model/main.go
Because
- init model script is using deprecated endpoints
This commit
- adopt namespace endpoints for init model
> chore(model): adopt namespace endpoints for init model

- go.mod
- pkg/acl/acl.go
- pkg/datamodel/datamodel.go
- pkg/datamodel/datamodel_test.go
- pkg/db/migration/convert/convert000008/convert.go
- pkg/repository/repository.go
- pkg/service/const.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
Because
- Provide users the ability to create custom tags for model
This commit
- allow custom tags for model
> feat(tag): allow custom tags for model

- go.mod
- go.sum
- pkg/datamodel/datamodel.go
- pkg/repository/repository.go
- pkg/service/convert.go
Because
- GetNamespaceModel should return all its associated version names, to improve the loading speed of Model component.
This commit
- embed version names in model message
> feat(version): embed version names in model struct

- pkg/db/migration/migration.go
- pkg/handler/create.go
- pkg/handler/public.go
- pkg/service/service.go
Because
- We will allow private models in CE version
This commit
- allow private model creation
> refactor(pkg): allow private model creation

- pkg/repository/transpiler.go
Because
- The SQL transpiler is not working correctly when using the AND operation
This commit
- fix the SQL transpiler bug
> fix(transpiler): fix expression

- cmd/worker/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/minio/minio.go
- pkg/minio/minio_test.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
Because
- model backend needs to store trigger input & output & files
This commit
- added minio connection
> feat(minio): added minio connection

- cmd/worker/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/minio/minio.go
- pkg/minio/minio_test.go
Because
- we need file link to minio for access and file size for preview
This commit
- return URL and uploaded file size, will store them later
> feat(minio): upgraded to minio v7 and return url and file size

- go.mod
- go.sum
- pkg/handler/mock_service_test.go
- pkg/mock/mock_repository.go
- pkg/repository/repository.go
- pkg/service/service.go
- pkg/service/utils.go
- pkg/utils/utils.go
Because
- run view permission updated
This commit
- updated by checking owner or not, public/private
> chore(run): fix run query API view permission

- go.sum
- pkg/handler/public.go
- pkg/handler/trigger.go
- pkg/ray/const.go
- pkg/ray/ray.go
- pkg/service/service.go
- pkg/service/worker.go
- pkg/worker/mock_ray_test.go
- pkg/worker/workflow.go
Because
- prevent request from blocking if model will undergo resource provisioning and scaling
- current operation error will have blank message
This commit
- support triggering upscale without blocking request
- populate error message field if operation failed
resolves INS-5927
resolves INS-5919
> feat(ray): support triggering upscale

- pkg/worker/workflow.go
Because
- enable usage consumption along with run logging
This commit
- enable usage consumption
> chore(usage): enable usage consumption

- pkg/mock/mock_repository.go
- pkg/repository/repository.go
- pkg/service/service.go
- pkg/usage/usage.go
- pkg/worker/workflow.go
Because
- for either private or public resources, owner could view all logs
This commit
- fix run logging owner view permission
> feat(run): fix run logging owner view permission

- pkg/handler/trigger.go
- pkg/worker/workflow.go
Because
- redis key for latest operation is wrongly set
This commit
- fix wrong redis key for latest operation
> chore(trigger): fix wrong redis key for latest operation

- pkg/worker/workflow.go
Because
- model start failure will cause workflow to run until context expiration
This commit
- exit activity if model state is not in a transition state
- add sleep time for state check
> chore(workflow): exit activity on error and add sleep time

- config/config.yaml
Because
- content type title has been updated
This commit
- update schema version
> chore(schema): update schema version

- pkg/datamodel/jsonschema.go
Because
- model-name property is not required for instill model
This commit
- remove model name property dynamically
> refactor(schema): remove model name property dynamically

- assets/model-dummy-chat/model.py
- assets/model-dummy-completion/model.py
- assets/model-dummy-multimodal-chat/model.py
- assets/model-dummy-multimodal-embedding/README.md
- assets/model-dummy-multimodal-embedding/instill.yaml
- assets/model-dummy-multimodal-embedding/model.py
- assets/model-dummy-text-embedding/model.py
Because
- we are missing multimodal embedding test model
This commit
- add multimodal embedding test model
> chore(test): add multimodal embedding test model

- .github/workflows/integration-test.yml
- .github/workflows/test-images.yml
Because
- we are missing multimodal embedding model in workflow
This commit
- add multimodal embedding model in workflow
> ci(workflow): add multimodal embedding model in workflow

- .github/workflows/integration-test.yml
- .github/workflows/test-images.yml
- assets/model-dummy-multimodal-chat-with-sleep/README.md
- assets/model-dummy-multimodal-chat-with-sleep/instill.yaml
- assets/model-dummy-multimodal-chat-with-sleep/model.py
Because
- We need a more realistic model with longer inference time for testing
This commit
- add sleep model and update test
> ci(workflow): add sleep model and update test

- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- occasionally upscale will fail due to state check
This commit
- fix upscale deployment failure
> fix(ray): fix upscale deployment failure

- .github/workflows/test-images.yml
- assets/model-dummy-ocr/instill.yaml
- assets/model-dummy-ocr/model.py
Because
- ocr dummy model is missing
This commit
- add ocr dummy model
> chore(models): add ocr dummy model

- cmd/main/main.go
- config/config.go
- go.mod
- go.sum
- pkg/service/service.go
- pkg/usage/usage.go
- pkg/worker/workflow.go
Because
- run logging metadata retention
This commit
- import updated minio package and add tag on file upload
> feat(minio): import updated minio package and add tag on file upload

- cmd/main/main.go
- cmd/worker/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/handler/mock_service_test.go
- pkg/handler/trigger.go
- pkg/mock/generator.go
- pkg/repository/influx.go
- pkg/service/collect.go
- pkg/service/service.go
- pkg/service/service_test.go
- pkg/utils/utils.go
- pkg/worker/utils.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- dashboard needs API for model trigger count
This commit
- write data for usage by new metrics API
> feat(run): write data for usage by model trigger chart record api

- config/model/model.json
- go.mod
- go.sum
- pkg/handler/public.go
Because
- provide display name for hardware types
This commit
- add title for region hardware
> feat(handler): add title for region hardware

- pkg/ray/ray.go
Because
- fix potential deployment config loss when pod restart
This commit
- fix potential deployment config loss when pod restart
> fix(ray): fix potential loss of deployment config

- go.mod
- go.sum
- pkg/ray/ray.go
Because
- the `model.ray` protobuf has been updated
This commit
- adopts the latest protobuf
> fix(ray): fix the wrong proto service

- go.mod
- go.sum
This commit
- updates x package
> chore(x): update x package to v0.10.0-alpha
