- README.md
- examples-go/grpc_client.go
- go.mod
- go.sum
- internal/db/migrations/000001_init.down.sql
- internal/triton/consts.go
- internal/triton/triton.go
- pkg/models/model.go
- pkg/repository/model.go
- pkg/services/model.go
- rpc/model.go
- scripts/quick-download.sh
Because
- User know CV Task when creating a model, then it is convenient to add CV Task at that point
This commit
- Move CV Task from PredictModel method to CreateModel method
> refactor: move cvtask from PredictModel method to CreateModel method

- docker-compose.yml
Because
- building docker dev image is an easy way for user who want to run model-backend from source code
This commit
- update docker-compose to build dev docker image
- close #28
> fix: update docker compose file for building dev image

- Dockerfile
- README.md
- cmd/main.go
- conda-pack/README.md
- conda-pack/python-3-8.tar.gz
- configs/config.yaml
- docker-compose.yml
- examples-go/grpc_client.go
- go.mod
- go.sum
- internal/constants.go
- internal/db/db.go
- internal/triton/triton.go
- pkg/repository/model.go
- pkg/services/model.go
- rpc/model.go
- rpc/payload.go
- scripts/quick-download.sh
Because
- besides making predictions via form-data (for REST API) and stream (for gRPC), the model-backend should support inference through URL/base64 image
This commit
- add predict method for input URL/base64
- closes #26 
- closes #27 
- closes #36
> feat: support url/base64 content prediction

- .github/.codecov.yml
- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
- .github/workflows/coverage.yml
Because
- we would like to regularly check test coverage of the codebase
This commit
- set up codecov action
- make GitHub Actions workflow name consistent
- close #45 
Note: origin [PR](https://github.com/instill-ai/model-backend/pull/35) quite out of date, many conflicts when merging into the main branch. So this PR cherry-pick commits related codecov from that
> ci: add codecov action

- internal/util/util.go
- pkg/handler/handler.go
Because
- Readme file exists if creating a model failed
This commit
- Remove Readme file if creating a model failed
> fix: remove readme file when error

- Dockerfile
- internal/util/util.go
Because
- GitHub LFS have limited quotation then support DVC tool to make a bridge between GitHub and Cloud Storage for model large files
This commit
- Add DVC tool to pull models from cloud storage
> chore: support dvc in GitHub model

- config/config.go
- config/config.yaml
- internal/external/external.go
Because
- support connecting to usage backend with both tls or not
This commit
- add tls config for usage backend
> chore: add tls config for usage backend

- config/credential/gcs_service_account.json
- config/credential/gcs_user_account.json
- config/init/instill/seed/credential_definitions.yaml
- config/init/instill/seed/model_definitions.yaml
- internal/util/const.go
- internal/util/util.go
- pkg/datamodel/credential.go
- pkg/datamodel/jsonschema.go
Because
- credential definition needs for both frontend and backend validation
This commit
- add Gcloud credential definition user account and service account
> feat: add credential definition

- .github/workflows/add-pr-to-prj.yml
- go.mod
- go.sum
- internal/triton/const.go
- internal/triton/triton.go
- internal/triton/util.go
- internal/util/util.go
- pkg/handler/handler.go
- pkg/service/service.go
Because
- decode output triton and format as a standardized output for unspecified task
This commit
- format output of unspecified task
- close #138
> chore: update output format of unspecified task

- go.mod
- go.sum
- integration-test/rest.js
- integration-test/rest_create_model.js
- integration-test/rest_infer_model.js
- pkg/handler/handler.go
- pkg/handler/mock_service_test.go
- pkg/service/service.go
Because
- `task` is shared among all batch outputs, it should be at the same level of `batch_outputs`
This commit
- adopt the latest protobuf to move task field one level up.
- rename `ModelInstanceInferenceResponse` to `ModelInstanceOutput`
> chore: adopt lastest protobuf

- config/init/instill/seed/model_definitions.yaml
Because
- update documentation URL with online pages
This commit
- update documentation URL in model definitions
- close #148
> chore: update documentation url with online page

- go.mod
- go.sum
- pkg/handler/handler.go
- pkg/handler/mock_service_test.go
- pkg/service/service.go
Because
- `batch_output` and its repeated field `batch_outputs` are used in the new protobuf.
This commit
- adopt the latest protobuf naming.
> chore: adopt latest protobuf

- go.mod
- go.sum
- pkg/handler/handler.go
- pkg/handler/mock_service_test.go
- pkg/service/service.go
Because
- naming consistency
This commit
- rename BatchOutput to TaskOutput
> refactor: rename BatchOutput to TaskOutput

- pkg/handler/handler.go
Because
- description should come from a single source (user input)
This commit
- update description for GitHub model from user input parameter
> fix: update description for GitHub model from user input

- cmd/init/db.go
Because
-  run init database container again and got the error duplicate key
This commit
- if already initialized database then continue to run
> chore: update init database

- pkg/handler/handler.go
Because
- when running an integration test in the console or other services, the internet connection could impact to test result. So use dummy model for integration test to make test result stable
This commit
- add dummy model for ArtiVC model
> chore: update dummy ArtiVC model for integration test

- Makefile
- pkg/handler/handler.go
Because
- Github model get tags that have limited request per day. So to reduce impact in the integration test, create  a dummy GitHub tag 
during testing 
This commit
- create Github dummy tag in integration test mode
> chore: update dummy GitHub

- cmd/main/main.go
- config/config.yaml
- pkg/usage/usage.go
Because
- usage service could be not available and the mgmt server should be resilient with this situation.
This commit
- check the connection to the usage service then report only have a connection
> chore: resilient with usage service not working

- pkg/handler/handler.go
Because
- VDP pipeline inference with 4 channels image broken
This commit
- compress 4 channels images into 3 channel images
> fix: 4 channels image inference with stream API

- config/config.go
- config/config.yaml
- internal/util/const.go
- pkg/handler/payload.go
Because
- max image size should be configurable
This commit
- add `maximagesize` in server config
> chore: add server config maximagesize

- pkg/handler/payload_test.go
Because
- max file image size is configurable
This commit
- update config of max image file size in payload test
> chore: update config max file size for payload unittest

- Makefile
- integration-test/const.js
Because
- the original env variable `HOSTNAME` conflicts with the default container `HOSTNAME` 
This commit
- rename `HOSTNAME` to `HOST`
> ci: rename env varible HOSTNAME to HOST

- pkg/repository/repository.go
Because
- gorm does not update zero value when using struct
This commit
- use map for updating unspecified (zero value) model instance state
> fix: model instance state update to unspecified state

- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
- README.md
- integration-test/proto/model.proto
Because
- instead of Visual Data Preparation, VDP is Versatile Data Pipeline now. We realise that as a general ETL infrastructure, VDP is capable of processing all kinds of unstructured data, and we should not limit its usage to only visual data. That's why we replace the word Visual with Versatile. Besides, the term Data Preparation is a bit misleading, users often think it has something to do with data labelling or cleaning. The term Data Pipeline is definitely more precise to capture the core concept of VDP.
This commit
- update to Versatile Data Pipeline
> chore: update Visual Data Preparation to Versatile Data Pipeline

- .env
- .github/workflows/coverage.yml
- .github/workflows/images.yml
- Dockerfile
- Dockerfile.dev
- Makefile
- cmd/main/interceptor.go
- cmd/main/main.go
- go.mod
- integration-test/const.js
- integration-test/grpc.js
- integration-test/grpc_create_model.js
- integration-test/grpc_deploy_model.js
- integration-test/grpc_infer_model.js
- integration-test/grpc_publish_model.js
- integration-test/grpc_query_model.js
- integration-test/grpc_query_model_definition.js
- integration-test/grpc_query_model_instance.js
- integration-test/grpc_update_model.js
Because
- `api-gateway` is used for localhost integration test (outside container) from now on
This commit
- adopt the latest api-gateway CI setting
- tinker codes
> ci: adopt api-gateway

- integration-test/const.js
- integration-test/grpc.js
- integration-test/grpc_create_model.js
- integration-test/grpc_deploy_model.js
- integration-test/grpc_infer_model.js
- integration-test/grpc_publish_model.js
- integration-test/grpc_query_model.js
- integration-test/grpc_query_model_definition.js
- integration-test/grpc_query_model_instance.js
- integration-test/grpc_update_model.js
Because
- the `api-gateway` supports h2c for gRPC over plaintext
This commit
- change the gRPC integration test protocol from `https` to `http`
> test: use http for api-gateway

- cmd/worker/main.go
- internal/util/const.go
- internal/worker/model.go
- internal/worker/worker.go
- pkg/handler/handler.go
- pkg/service/service.go
- pkg/service/worker.go
Because
- update ready endpoint
This commit
- check Temporal 's search attribute ready in the ready endpoint
> chore: update ready enpoint to check search attribute ready

- cmd/worker/main.go
- config/config.yaml
Because
- `ITMODE` should be set to true for local development
- Temporal provides no API for checking the readiness of namespace created in the Temporal cluster. Waiting for 10s looks to be the only solution at the moment according to the official [doc](https://docs.temporal.io/application-development/features#register-namespace):
```
Note that Namespace registration using this API takes up to 10 seconds to complete. 
Ensure that you wait for this registration to complete before starting the Workflow 
Execution against the Namespace.
```
This commit
- set `ITMOD=true` in `config.yaml`
- add sleep for 10 seconds when launching the Temporal worker
> chore: tinker codes

- config/config.go
- config/config.yaml
- internal/external/external.go
- internal/triton/triton.go
- pkg/handler/payload.go
- pkg/handler/payload_test.go
Because
- to make configuration variables consistent across different repos
This commit
- rename configuration variables accordingly
> refactor: rename config variables

- cmd/main/interceptor.go
- cmd/main/main.go
- cmd/main/middleware.go
- pkg/usage/usage.go
Because
- fields naming related to mgmt-backend are wrong
This commit
- fix naming
> chore: rename mgmt fields and variables

- pkg/usage/usage.go
Because
- in case mgmt-backend is not ready, model-backend should not panic and crash
This commit
- fix the issue by breaking the usage report loop
> fix: fix usage client nil issue when mgmt-backend not ready

- Dockerfile
Because
- mounting points require `chown -R nobody:nogroup` for the production container
This commit
- fix it accordingly
> ci: fix permission issue in /model-repository

- internal/util/util.go
Because
- diffusion model has `.bias` and `.weight` extension for model weight file
This commit
- add `.bias` and `.weight` extension when finding the model weight
> chore: check model file with prefix suffix

- pkg/handler/payload.go
Because
- missing keypoint model payload parser
This commit
- add keypoint model payload parser
> fix: fix keypoint model payload parser

- internal/worker/model.go
Because
- deploying a huge model take a long time to download the model weight
This commit
- increase deployment model activity timeout to 300 minutes
> chore: update deploy activity timeout to 300 minutes

- internal/triton/triton.go
- pkg/handler/payload.go
Because
- image output of diffusion model should be image for easy to use
This commit
- encode jpeg image for diffusion output images
> chore: encode output of diffusion model

- pkg/service/service.go
Because
- inference output format needs to be consistency even when having an empty output
This commit
- add empty output in case of having no result
> fix: keep format for empty inference output

- internal/triton/triton.go
Because
- make inference timeout consistency with the api-gateway
This commit
- change inference timeout to 5 minutes
> chore: change inference timeout to 5 minutes

- pkg/handler/payload.go
Because
- there is an issue related to buffer size sending from gRPC server to the client. Now only send a single image in response
This commit
- limit text-to-image output samples to 1
> chore: limit samples of generated images by text-to-image model to 1

- Dockerfile
Because
- the model-backend uses`/tmp` folder during working with model
This commit
- add user permission for `/tmp` folder
> chore: add user permission for /tmp folder

- internal/triton/triton.go
Because
- inference could be slow on CPU
This commit
- increase inference timeout to 10 minutes
> chore: increase inference timeout to 10 minutes

- internal/util/file.go
- internal/util/util.go
- internal/worker/model.go
- pkg/handler/handler.go
Because
- avoid piling up dvc files in model store
This commit
- add logic clause to not copying dvc related files into model store
Closes #279
> chore: update utility for file matching

- internal/util/file.go
Because
- need to create a subfolder `users` when creating a model in `model-repository`
This commit
- add code to check parent folder and create it if not existed
- close #288
> fix: create a subfolder in model-repository if needed

- internal/util/util.go
Because
- some model weight files have no suffix
This commit
- find the model weight files by prefix
> chore: add find by prefix for model weight files

- pkg/handler/handler.go
Because
- there are Triton health checks in liveness and ready endpoint
This commit
- remove checking Triton health in methods
> chore: remove checking triton health in model inference method

- config/config.go
- config/config.yaml
- go.sum
- internal/external/external.go
Because
- the mgmt-backend port used is the private port
This commit
- fix mgmt backend port naming
> fix(config): use private port for mgmt-backend

- Dockerfile
- Dockerfile.dev
- Makefile
- config/config.go
- config/config.yaml
- pkg/handler/public_handler.go
- pkg/triton/triton.go
- pkg/util/const.go
- pkg/util/file.go
- pkg/util/util.go
- pkg/worker/model.go
Because
- the model downloading time is quite long for huge models
This commit
- support caching model into` ~/.cache/instill/models` when enabling the config `cache.model = true`
> feat: support model caching

- Dockerfile.dev
Because
- support a caching model in model-backend
This commit
- add cache dir in Dockerfile
> chore: create cache dir in Dockerfile

- config/init/instill/seed/model_definitions.yaml
- pkg/handler/public_handler.go
Because
- model local and huggingface do not support tag
This commit
- remove tag for local model and huggingface in model-definition
> chore: remove tag for local and huggingface model

- integration-test/grpc_model_operation.js
Because
- `ListModelOperations` is flaky since the response field won't exist if an operation is not done 
This commit
- fix the `ListModelOperations` test
> test: refactor ListModelOperations test

- pkg/handler/private_handler.go
- pkg/handler/public_handler.go
- pkg/service/controller.go
- pkg/service/service.go
- pkg/service/service_test.go
- pkg/service/worker.go
Because
- use a single context for all package layers such as service, and triton.
This commit
- add context in service interface
> fix: pass the context between package layers

- integration-test/rest_create_model_with_jwt.js
- integration-test/rest_deploy_model_with_jwt.js
- integration-test/rest_infer_model_with_jwt.js
- integration-test/rest_model_card_with_jwt.js
- integration-test/rest_publish_model_with_jwt.js
- integration-test/rest_query_model_with_jwt.js
- integration-test/rest_update_model_with_jwt.js
- internal/resource/resource.go
- pkg/handler/public_handler.go
Because
- currently, if a user does not exist in mgmt-backend, returns 500 status error
This commit
- return 404 when a user does not exist
- return 401 when both `jwt-sub` and `owner-id` does not exist in the header 
- update tests
> chore: return 404 for non-exist user and 401 for non-existent headers

- cmd/main/main.go
- cmd/worker/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/handler/public_handler.go
Because
- for users who like to connect with Temporal Cloud directly, currently the only way is by mTLS auth
This commit
- enables Temporal client TLS configuration
> chore: set up connector-backend mTLS connection for Temporal

- config/config.go
Because
- the temopral config struct tags are missing
This commit
- add the corresponding tags
> chore: fix missing config struct tags

- cmd/model/main.go
Because
- the model initialization failed if rerun it
This commit
- ignore the model if it already existed
- INS-574
> chore: continue run init model if the model already existed

- cmd/main/main.go
- pkg/handler/public_handler.go
- pkg/logger/logger.go
- pkg/middleware/middleware.go
- pkg/service/service.go
- pkg/triton/triton.go
Because
- grpc triton client should not create per multipart request
This commit
- create a single triton client and pass to multipart handler methods
> fix: create single triton client

- .github/workflows/integration-test.yml
- Makefile
- integration-test/const.js
- integration-test/grpc.js
- integration-test/rest.js
- integration-test/rest_with_jwt.js
Because
- Need to simplify the integration test mode
This commit
- Add `API_GATEWAY_HOST`, `API_GATEWAY_PORT` and `API_GATEWAY_PROTOCOL` var. to simplify the integration test setting
> chore: refactor integration test mode

- pkg/datamodel/datamodel.go
- pkg/repository/repository.go
- pkg/service/mock_repository_test.go
- pkg/worker/model.go
- pkg/worker/utils.go
Because
- avoid pipelines become orphan when redeploying models and db
This commit
- fix the uuids of predeploy models
> chore: fix predeploy model uuid

- cmd/model/main.go
- pkg/worker/utils.go
Because
- unauthenticated when using `INITMODEL_ENABLED` with predefined owner
This commit
- fix by bypassing predefined owner id, need further testing for cloud
> chore: fix owner id not matched

- .github/workflows/integration-test.yml
- assets/model-dummy-cls/post/1/model.py
- assets/model-dummy-cls/pre/1/model.py
- cmd/init/main.go
- cmd/model/main.go
- go.mod
- go.sum
- pkg/handler/private_handler.go
- pkg/handler/public_handler.go
Because
- allow `controller-model` to move `model` current state to desire state
This commit
- add deploy/undeploy private method for `controller-model`
> chore: add private methods for controller-model

- cmd/main/main.go
- cmd/worker/main.go
- go.mod
- go.sum
- pkg/handler/public_handler.go
- pkg/service/mock_triton_test.go
- pkg/service/service.go
- pkg/service/service_test.go
- pkg/triton/triton.go
- pkg/worker/model.go
Because
- provide clearer view of span life cycle for observability
This commit
- add support for context propagation to temporal worker
> chore(logging): support context propagation to temporal worker

- pkg/handler/private_handler.go
- pkg/handler/public_handler.go
- pkg/util/util.go
Because
- deploy model will fail if model-repository is empty but db has model records
This commit
- reclone and repopulate model-repository with model records in db
> chore: reclone and convert model structure if missing in model repo

- config/config.go
- config/config.yaml
- pkg/service/worker.go
- pkg/worker/model.go
Because
- prevent errored workflow from running endlessly
This commit
- add max retry limit for workflow/activity
> chore(temporal): add max retry to prevent never ending workflows

- cmd/main/main.go
- cmd/model/main.go
- pkg/handler/mock_service_test.go
- pkg/handler/payload.go
- pkg/handler/private_handler.go
- pkg/handler/public_handler.go
- pkg/logger/otel/const.go
- pkg/service/collect.go
- pkg/service/controller.go
- pkg/service/service.go
- pkg/usage/usage.go
- pkg/utils/const.go
- pkg/utils/file.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- pkg/worker/model.go
- pkg/worker/utils.go
Because
- avoid error-prone implementation of redis cache datatype
This commit
- update redis cache datatype
- add usage enabled check before write into redis
- fix `util` package naming
> chore(usage): fix redis cache datatype

- go.mod
- go.sum
- pkg/usage/usage.go
Because
- avoid complex query for usage metrics
This commit
- adopt new usage-client to add `owner_uid` in session
> chore(usage): adopt new usage-client to include owner_uid in session

- cmd/model/main.go
- pkg/handler/private_handler.go
Because
- missing parent path in predeploy and private model create request
This commit
- add `parent` param
> chore(controller): fix predeploy and private create parent path

- pkg/worker/utils.go
Because
- fix deleting and recreating predeploy model will fail with duplicate uuid
This commit
- consider predeploy models only in cloud environments
> chore: fix predeploy model visibility and uid

- go.sum
- pkg/constant/constant.go
- pkg/service/service.go
Because
- centralize api_token validation in api-gateway
This commit
- remove api_token validation
> chore: remove api-token validation

- go.mod
- go.sum
- pkg/handler/private_handler.go
- pkg/handler/public_handler.go
- pkg/usage/usage.go
Because
- the grpc-gateway will convert `int64` to `string`
This commit
- use `int32` for `page_size`, `total_size` and `file_length` to avoid this problem
> refactor(handler): adopt 32bit int type in request

- pkg/constant/constant.go
- pkg/service/service.go
Because
- the `user_id` injection in backend is unsafe
- we are going to change the default_user_id to `admin`
This commit
- remove `user_id` injection
- change the default_user_id to `admin`
> chore(service): remove unsafe user_id injection and update default_user_id

- cmd/main/main.go
- pkg/service/service.go
- pkg/service/service_test.go
Because
- the `user_id` injection in backend is unsafe
This commit
- remove `user_id` injection
> chore(service): remove unsafe user_id injection

- cmd/model/main.go
- pkg/constant/constant.go
Because
- predeploy/public models should be owned by `instill-ai` instead of `admin`
This commit
- update predeploy model namespace
> chore(main,constant): update predeploy model namespace

- cmd/model/main.go
Because
- namespace mismatched between header and request body
This commit
- fix jwt header uid
> chore(main): fix jwt header uid

- cmd/main/main.go
- go.sum
- integration-test/rest.js
- pkg/triton/triton.go
Because
- Currently backends in Instill Base Instill VDP and Instill Model will emit a huge amount of logs with level Info, which can overwhelm stdout
This commit
- Refactor grpc logger `verbosity` and bypass successful private function calls
closes instill-ai/community#436
> refactor(logging): reduce unnecessary log emission

- pkg/triton/triton.go
- pkg/utils/utils.go
Because
- To enhance TRITON Inference Server's capabilities by supporting LLM-like models such as Llama through the vLLM and python operator.
This commit
- Enable support for module files with postfixes: model, json, and sagetensors.
- Introduce an improved filename parser. (Note: There's a TODO to develop a more generalized function for detecting file structure.)
> feat(model): Support for LLM-like models in TRITON Inference Server

- config/config.yaml
- pkg/utils/utils.go
Because
- to support Llava Model
- move the model_hub_* files from vdp to model
This commit
- added functionality to identify the llava folder in utility functions.
- relocated the model_hub_* files from the vdp directory to the model directory.
> feat(model): Enhancements for Llava Model Support and Model Hub File Movement

- cmd/model/main.go
- pkg/worker/utils.go
Because
- bypass predeploy model list
This commit
- bypass predeploy model list
> chore(model): update predeploy model logic

- Dockerfile
- Dockerfile.dev
- go.mod
- go.sum
Because
- Go 1.21 base image uses Python 3.11, which breaks the previous build
This commit
- update Dockerfiles
> fix(Dockerfile): fix Python 3.11 using Debian base image

- Dockerfile
- Dockerfile.dev
Because
- pipx install packages as executables, not lib
This commit
- update installation method
> chore(dockerfile): use venv instead of pipx

- pkg/handler/payload.go
- pkg/handler/public_handler.go
- pkg/triton/triton.go
- pkg/utils/const.go
Because
- avoid unbound int type conversion
This commit
- apply bound check and error handling by `ParseInt`
> fix(payload): fix incorrect conversion between integer types

- .github/workflows/integration-test.yml
- pkg/service/service.go
Because
- unable to delete model when model is in `STATE_ERROR`
This commit
- allow deletion when model no online or under longrunning operation
> fix(service): fix fail model deletion in state error

- Dockerfile
- Dockerfile.dev
- Makefile
- pkg/ray/ray.go
- pkg/utils/utils.go
Because
- avoid installing duplicate packages in `model-backend` container
This commit
- share python executable with `ray-server`
> feat(ray): use shared python executable

- pkg/service/service.go
- pkg/worker/model.go
Because
- avoid having false state in etcd
This commit
- fix marking model state as `STATE_ERROR` if model exist when creating
> chore(model): fix deployment reconciliation

- integration-test/proto/model/model/v1alpha/model.proto
Because
- the protobufs version of healthcheck is wrong
This commit
- fix protobufs version in test file
> chore(deps): fix protobufs version in test file

- go.mod
- go.sum
- pkg/handler/public_handler.go
- pkg/usage/usage.go
- pkg/utils/utils.go
Because
- adopt org and acl data collection for usage
This commit
- add `owner` and `user` data in each trigger and support user type
> chore(usage): adopt latest protobuf to add user/owner

- Dockerfile
- Dockerfile.dev
Because
- DVC 3.X version have permission issue to pull data from GS
This commit
- Rollback to 2.34 version
> chore(model): downgrade DVC version to 2.34

- pkg/ray/ray.go
Because
- sdk has updated the deploy flow
This commit
- adopt latest ray helper from sdk
> refactor(ray): adopt latest ray helper from sdk

- pkg/service/service.go
- pkg/worker/model.go
Because
- properly delete app on ray serve even if resource state is in `STATE_ERROR`
This commit
- allow model deletion in `STATE_ERROR`
> chore(model): undeploy faulty model in error state

- cmd/worker/main.go
- config/config.go
- config/config.yaml
- pkg/handler/public_handler.go
- pkg/utils/const.go
- pkg/utils/utils.go
- pkg/worker/model.go
- pkg/worker/worker.go
Because
- json file as model cache state introduces race condition when multiple models are deploying
This commit
- use redis to cache model files state
fixes ins-2909
> feat(redis): use redis for model state caching

- config/config.yaml
- pkg/utils/utils.go
Because
- use redis key naming convention
This commit
- update model cache key
> chore(redis): update model cache key

- go.mod
- go.sum
- pkg/ray/ray.go
Because
- Currently, text generation-related tasks only support inference without batch
This commit
- resolve batch size issues in text generation-related tasks
> chore(model): resolve batch size issues in text generation task

- integration-test/rest_create_model_with_jwt.js
- integration-test/rest_deploy_model_with_jwt.js
- integration-test/rest_infer_model_with_jwt.js
- integration-test/rest_model_card_with_jwt.js
- integration-test/rest_publish_model_with_jwt.js
- integration-test/rest_query_model_with_jwt.js
- integration-test/rest_update_model_with_jwt.js
- pkg/constant/constant.go
- pkg/handler/public_handler.go
- pkg/middleware/misc.go
- pkg/service/service.go
Because
- We need to standardize the naming convention of customized headers
This commit
- replace `Jwt-Sub` with `Instill-User-Uid`
> refactor(auth): replace `Jwt-Sub` with `Instill-User-Uid`

- cmd/main/main.go
- cmd/model/main.go
- config/config.go
- config/config.yaml
- pkg/constant/constant.go
Because
- discrepancy of available user between different version
This commit
- update usage and initmodel user to reference from config
> refactor(config): update usage and initmodel user

- cmd/model/main.go
- config/config.go
Because
- missing namespace for predeploy model request
This commit
- fix missing namespace
> chore(model): fix missing namespace

- config/init/instill/seed/model_definitions.yaml
- integration-test/grpc_query_model_definition.js
- integration-test/rest_query_model_definition.js
Because
- model spec needs to follow updated json schema fields to allow auto-gen form
- huggingface import will be refactored to support one-click import
This commit
- update model spec schema
- disable `huggingface` and `artivc` model source
> refactor(config): update model spec schema

- pkg/utils/utils.go
Because
- json file might be smaller than 200b
This commit
- exclude json file from file size check. weight file check login will be refactored in the future
> chore(utils): exclude json file from size check

- config/config.yaml
- pkg/ray/ray.go
Because
we are transitioning the majority of our models to be served via Ray, moving away from Triton.
This commit
**Models Transitioned to Ray Serving:**
- LLaMA2-7B
- LLaMA2-7B-Chat
- LLaVA-7B
- Zephyr-7B
- Stable Diffusion XL
- ControlNet-Canny
**Models Remaining on Triton:**
- YOLOv7-Pose
- Stomata-Mask R-CNN
- Fix Missing field on ray serve and enlarge grpc maxdatasize
> fix(model): fix missing field in ray while serving img2img task

- config/config.go
- config/config.yaml
- pkg/ray/ray.go
Because
- python-sdk now require deploy calls to include `vram` info to dynamically adjust `num_of_gpus` value
This commit
- add vram in config and `DeployModel` method
> chore(config,ray): add gpu vram info when deploying

- pkg/utils/utils.go
- pkg/worker/model.go
Because
- `hasModelWeight` is too generic and cause edge case errors
This commit
- add dedicated logic for dvc files
- has*Weight will be source specific in the future
> chore(utils): fix has model weight

- pkg/ray/ray.go
Because
- allow up to 10 minutes for infer request
This commit
- add timeout for infer calls
> chore(ray): add timeout for infer calls

- .github/workflows/codeql.yml
- .github/workflows/integration-test.yml
- Dockerfile
Because
- PR head integration-test will run out of disk space
This commit
- use min triton image to reduce disk size usage
> ci(workflows): use min triton image

- pkg/handler/payload.go
- pkg/handler/public.go
- pkg/utils/file.go
Because
- file close without error handling
This commit
- add error handling while closing file
> refactor(pkg): fix file close without error handling

- cmd/model/main.go
- config/config.go
- config/config.yaml
- pkg/middleware/misc.go
Because
- we now support creating and deploying models under org namespace
This commit
- support hosting predeploy models under org namespace
> refactor(cmd): support org namespace with predeploy models

- cmd/worker/main.go
- config/config.go
- config/config.yaml
Because
- make temporal namespace programmatically created to remove the `temporal-admin-tools` container at launch
This commit
- add initialisation temporal namespace logic in the worker `main.go`
- the implementation will skip the namespace creation if it already exists
> chore(worker): create temporal namespace at launch

- pkg/handler/create.go
Because
- if not properly clean up redis record will cause model creation issue
This commit
- clean up redis record if encounter errors when creating models
> chore(handler): delete redis record if model create error

- .github/workflows/integration-test.yml
Because
- we refactored the entire Instill project structure, the existing GA won't work.
This commit
- adopts latest project structure
> ci(workflows): adopt latest project structure

- Dockerfile.dev
- Makefile
- config/config.go
- config/config.yaml
- config/init/instill/seed/model_definitions.yaml
- go.mod
- integration-test/grpc_query_model_definition.js
- integration-test/rest_query_model_definition.js
- pkg/datamodel/datamodel.go
- pkg/handler/create.go
- pkg/handler/public.go
- pkg/ray/const.go
- pkg/ray/ray.go
- pkg/ray/undeploy.py
- pkg/service/service.go
- pkg/worker/model.go
Because
- Instill Model will support containerized model deployment
This commit
- add registry config
- add `container` model definitionn
- add `ray[serve]` for CLI support, ray-conda will be removed in the future
- support containerized model deployment/undeployment
Resolves INS-3719
Resolves INS-3837
> feat(ray): support containerized model deployment

- pkg/ray/ray.go
Because
- We now use nvidia CDI to access gpu instead of runtime hook injection
This commit
- specify CDI devices with `podman run` command
> chore(ray): add nvidia CDI gpu flag

- pkg/handler/private.go
- pkg/ray/ray.go
- pkg/service/service.go
- pkg/service/worker.go
- pkg/worker/model.go
Because
- We have decided to adopt the format of `{user-id}/{model-id}` for model repository name
- We are missing permission check for `DeployNamespaceModel`
This commit
- add `UserID` in repo name when pulling model iamge
- add permission check for `DeployNamespaceModel`
Resolves INS-3975
> chore(ray): adopt registry namespace format

- pkg/ray/const.go
- pkg/ray/ray.go
Because
- we will only allow model resource configuration from model-backend
This commit
- support model resource config env variables passthrough to ray
- lay the foundation for future customizable model deployment
> chore(ray): add model resource config envs

- pkg/ray/ray.go
Because
- we are removing available CPU resource on GPU node to prevent CPU model to schedule on GPU node
This commit
- remove cpu resource request for GPU model
> chore(ray): remove cpu resource request for gpu model

- pkg/ray/const.go
- pkg/ray/ray.go
Because
- We need to support GPU types other than the official accelerator type supported by [ray](https://docs.ray.io/en/latest/ray-core/accelerator-types.html)
This commit
- support custom accelerator type env
> feat(ray): support custom accelerator type

- .github/workflows/test-images.yml
- assets/model-dummy-cls/instill.yaml
- assets/model-dummy-cls/model.py
- assets/model-dummy-det/instill.yaml
- assets/model-dummy-det/model.py
- assets/model-dummy-image-to-image/instill.yaml
- assets/model-dummy-image-to-image/model.py
- assets/model-dummy-instance-segmentation/instill.yaml
- assets/model-dummy-instance-segmentation/model.py
- assets/model-dummy-keypoint/instill.yaml
- assets/model-dummy-keypoint/model.py
- assets/model-dummy-semantic-segmentation/instill.yaml
- assets/model-dummy-semantic-segmentation/model.py
- assets/model-dummy-text-generation-chat/instill.yaml
- assets/model-dummy-text-generation-chat/model.py
- assets/model-dummy-text-generation/instill.yaml
- assets/model-dummy-text-generation/model.py
- assets/model-dummy-text-to-image/instill.yaml
- assets/model-dummy-text-to-image/model.py
- assets/model-dummy-visual-question-answering/instill.yaml
- assets/model-dummy-visual-question-answering/model.py
- config/config.go
- config/config.yaml
Because
- We need to convert all existing test models into container format for integration-tests
This commit
- retire `ItMode` config
- converts test models into container format
- add test model build workflow
> test(model): convert test models to container format and add build workflow

- assets/model-dummy-cls/model.py
- assets/model-dummy-det/model.py
- assets/model-dummy-image-to-image/model.py
- assets/model-dummy-instance-segmentation/model.py
- assets/model-dummy-keypoint/model.py
- assets/model-dummy-semantic-segmentation/model.py
- assets/model-dummy-text-generation-chat/model.py
- assets/model-dummy-text-generation/model.py
- assets/model-dummy-text-to-image/model.py
- assets/model-dummy-visual-question-answering/model.py
Because
- new container model does not need positional argument and is causing errors
```
.__init__() missing 1 required positional argument: '_'
```
This commit
- remove positional argument in test model `__init__` function
> chore(test): fix test model init

- assets/model-dummy-image-to-image/instill.yaml
- assets/model-dummy-text-to-image/instill.yaml
Because
- Some test models are missing required packages
This commit
- add missing packages in model config
> fix(model): fix missing package in test models

- assets/model-dummy-image-to-image/instill.yaml
- assets/model-dummy-image-to-image/model.py
- assets/model-dummy-text-to-image/instill.yaml
- assets/model-dummy-text-to-image/model.py
Because
- some test model image has `torch` installed and is making them unreasonably large
This commit
- remove `torch` from test models
> chore(model): remove large package from test model

- pkg/service/service.go
Because
- ListModelVersions endpoint is returning list size of `PageSize` which is wrong
This commit
- fix `ListModelVersions` endpoint returned list size
> fix(service): fix list model version return list size

- go.mod
- go.sum
- pkg/handler/payload.go
- pkg/ray/const.go
- pkg/ray/preprocess.go
- pkg/service/convert.go
- pkg/utils/const.go
Because
- allow FE to show sample input/output payload on overview page
This commit
- embed sample input/output in model proto message
> feat(model): embed sample input/output in model proto message

- go.mod
- go.sum
- pkg/datamodel/jsonschema.go
- pkg/handler/public.go
Because
- We need to provide the info about supported regions and hardware for FE to render the model creation page
This commit
- add list available region method
> feat(handler): support listing available regions for model deployment

- .gitignore
- config/model/model.json
- pkg/ray/ray.go
Because
- Current spec schema blocks custom resource
This commit
- allow creating model with custom resource tag in local cluster
> chore(spec): fix wrong hardware schema

- pkg/ray/ray.go
Because
- We do not assume for the user how much vram does their model use
This commit
- set default num of gpu for generic gpu type to `1`
- allow setting total vram as config
> chore(ray): update default num of gpu

- pkg/service/service.go
Because
- Returned Version array is init with wrong size
This commit
- fix list model version pagination total size
> fix(service): fix list model version pagination

- pkg/handler/fieldannotation.go
- pkg/handler/public.go
- pkg/service/convert.go
- pkg/service/service.go
Because
- Patch model will result in error due to image string
- Patch model hardware won't trigger redeployment
- Visibility now only support changing through publish/unpublish endpoints, will be refactored soon
This commit
- fix update model behaviors
> chore(service): fix update model

- cmd/model/main.go
Because
- Missing task field when creating models in init model job
This commit
- add missing task field in model creation request
> chore(init): fix missing task field

- .github/workflows/integration-test.yml
- pkg/ray/ray.go
Because
- accelerator type default to fractional of `0.001` and its causing auto-scaling problems
This commit
- set custom resource label along with accelerator type
> chore(ray): set custom resource along with acc type

- pkg/service/convert.go
Because
- We are missing `readme` in the GET model response
This commit
- add missing `readme` field in conversion
> chore(service): fix missing readme in response

- config/model/task.json
- config/model/task_input.json
- config/model/task_output.json
- go.mod
- go.sum
- pkg/datamodel/jsonschema.go
- pkg/ray/rayserver/ray_server.proto
- pkg/service/convert.go
- pkg/service/service.go
Because
- FE needs input and output schema for trigger form rendering
This commit
- add schema fields for model input and output in model struct
- add view filter logic in conversion
> feat(model): add task schema in model struct

- pkg/ray/ray.go
Because
- Force custom resource label on ray application has not effect on auto-scaling issue
This commit
- revert commit https://github.com/instill-ai/model-backend/commit/ea5a85ede67da92ce8aa824f7b97109ac302de7f
> chore(ray): revert forcing custom resource label

- pkg/ray/ray.go
- pkg/repository/repository.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
Because
- `accelerator_type` seems to cause auto-scaling issue
This commit
- replace acc type with custom resource
> chore(ray): replace acc type with custom resource

- pkg/service/service.go
Because
- ListModelVersions will return 404 if one of the version is not found in Ray
This commit
- return `ERROR` state for missing Ray application instead of 404 as a whole
> chore(service): return error state instead of 404

- pkg/handler/public.go
Because
- Redeployment is wrongly triggered when `hardware` field is not in the update mask
This commit
- update field extraction in UpdateModel method
> chore(handler): update field extraction

- go.mod
- go.sum
- pkg/handler/public.go
- pkg/repository/repository.go
- pkg/repository/utils.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
Because
- Model hub page support `order_by` option
- Model banner needs to show latest model state
This commit
- implement `order_by` input query string
- add watch latest model endpoints
resolves INS-4775
> feat(model): support watch latest model and `order_by` for list endpoints

- pkg/handler/payload.go
- pkg/ray/ray.go
Because
- State should be `Offline` when there is 0 replica of a certain model version
- BE should handle `image_base64` input with mime type
This commit
- update ray application status
- trim mime from `base64` string
> chore(ray): show offline when replica number is 0

- pkg/handler/fieldannotation.go
- pkg/handler/public.go
- pkg/service/service.go
Because
- User should be allowed to `PATCH` model visibility
- should not redeploy if `hardware` type is not changed
This commit
- remove visibility restriction in update endpoint
- fix `hardware` update check
> chore(handler): allow visibility patch and fix hardware update

- go.mod
- go.sum
- pkg/ray/ray.go
Because
- BE should not return `STATE_UNSPECIFIED` to client
This commit
- describe resource provisioning with `STATE_STARTING`
> chore(ray): adopt starting state to describe resource provisioning

- .github/workflows/test-images.yml
- cmd/model/main.go
- config/config.go
- config/config.yaml
Because
- Predeploy model lists has models which will be deployed under different namespace
This commit
- allow deploying models under different namespace
- update test images' tag
> chore(model): allow deploying models under different namespace

- config/model/task_input.json
Because
- Trigger form on FE cannot provide the necessary payload object with the current schema, add a temporary field to allow FE to construct the correct trigger payload
- This addition should be temporary, proper design will follow
This commit
- add `instillModelPromptImageBase64ObjectFormat` for FE to construct a fixed payload object as a workaround
> chore(schema): add temporary field to toggle object image input

- config/model/task_input.json
Because
- Chat history field on console is not usable
This commit
- remove chat_history field in input schema
> chore(schema): remove chat history from input schema

- integration-test/grpc.js
- integration-test/rest.js
- integration-test/rest_with_jwt.js
- pkg/utils/const.go
Because
- Currently, our API HTTP request and response bodies are a mix of camelCase and snake_case, which is not consistent.
This commit
- Uses camelCase for HTTP bodies.
> feat(handler): use camelCase for HTTP body

- integration-test/grpc_create_model.js
- integration-test/grpc_deploy_model.js
- integration-test/grpc_deploy_model_private.js
- integration-test/grpc_publish_model.js
- integration-test/grpc_query_model.js
- integration-test/grpc_query_model_definition.js
- integration-test/grpc_query_model_private.js
- integration-test/grpc_update_model.js
- integration-test/rest_create_model.js
- integration-test/rest_create_model_with_jwt.js
- integration-test/rest_deploy_model.js
- integration-test/rest_deploy_model_private.js
- integration-test/rest_deploy_model_with_jwt.js
- integration-test/rest_infer_github_model.js
- integration-test/rest_infer_model.js
- integration-test/rest_longrunning_operation.js
- integration-test/rest_model_card.js
- integration-test/rest_model_card_with_jwt.js
- integration-test/rest_publish_model.js
- integration-test/rest_publish_model_with_jwt.js
- integration-test/rest_query_model.js
- integration-test/rest_query_model_definition.js
- integration-test/rest_query_model_private.js
- integration-test/rest_query_model_with_jwt.js
- integration-test/rest_update_model.js
- integration-test/rest_update_model_with_jwt.js
- pkg/handler/private.go
- pkg/handler/public.go
- pkg/repository/repository.go
- pkg/repository/transpiler.go
Because
- We should use camelCase for query strings to align with the HTTP body.
This commit
- Updates query strings `filter` and `orderBy` to use camelCase.
> feat(endpoints): use camelCase for `filter` query string

- pkg/repository/repository.go
- pkg/repository/transpiler.go
Because
- The `pageToken` is not correctly encoded due to the refactor to camelCase.
This commit
- Fixes the `pageToken` bug.
> chore(repository): fix pageToken bug

- cmd/migration/main.go
- go.mod
- go.sum
- pkg/db/migration/000006_init.up.sql
- pkg/service/service.go
Because
- id is ambiguous, use `version` instead
This commit
- rename `id` to `version`
- use updateTime in model db record
> refactor(version): update model version name and updateTime

- .gitignore
- config/config.yaml
- pkg/datamodel/datamodel.go
- pkg/db/migration/000007_remove_model_prediction.down.sql
- pkg/db/migration/000007_remove_model_prediction.up.sql
- pkg/handler/mock_service_test.go
- pkg/handler/stream.go
- pkg/handler/trigger.go
- pkg/repository/repository.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
- pkg/worker/workflow.go
Because
- model prediction data struct is not needed anymore
This commit
- removed the struct and related functions
> refactor(all): remove model prediction and related functions

- pkg/service/service.go
Because
- We need to expose ray client for custom auto-scaling config logic
This commit
- add method to expose ray client
> chore(service): add method to expose ray client

- pkg/repository/transpiler.go
Because
- When performing fuzzy searches on models, case-insensitivity should be allowed.
This commit
- Supports case-insensitive searches for models.
> feat(repository): support case-insensitive search models

- .github/workflows/integration-test.yml
Because
- PR integration-test workflow does not wait for test model to be deployed
This commit
- fix PR integration-test by waiting for test models to be deployed
> ci(workflows): fix integration-test

- go.mod
- go.sum
- pkg/handler/private.go
- pkg/service/service.go
Because
- model-backend should check the existence of the repo tag before deploying the model on Ray, to prevent fail deployment
This commit
- add repo tag check in admin deploy endpoint
> chore(handler): add get repo tag

- pkg/constant/constant.go
- pkg/handler/trigger.go
- pkg/service/service.go
- pkg/worker/workflow.go
Because
- some entrypoint did not cover credit check for `TriggerModelWorkflow`
This commit
- moved `Check` to wrap the call to Ray
> feat(credit): refactored check and collect for model trigger

- pkg/ray/ray.go
Because
- `Sync` does not provide model name to deploy
This commit
- check action before extracting metadata value
> chore(ray): fix metadata model name

- pkg/datamodel/datamodel.go
- pkg/service/service.go
Because
- Users can provide the `Instill-Requester-Uid` in order to trigger models on behalf of an organization.
This commit
- Limits the execution permissions when an organization namespace is
used to trigger a model. It checks:
- User can impersonate the organization
- If an organization is the requester and doesn't own the model, model has to be public
> feat(service): check trigger permissions when impersonating an org

- pkg/repository/repository.go
Because
- Get model endpoints does not return model tags
This commit
- add missing tag query
> fix(repository): fix missing tag query

- pkg/handler/trigger.go
- pkg/minio/minio.go
Because
- inputs at some trigger points are byte array
This commit
- added a function for taking byte array as param
> feat(minio): added minio upload file bytes function

- pkg/handler/stream.go
- pkg/handler/trigger.go
- pkg/service/service.go
Because
- We cannot use the same redis key for sync trigger input and async trigger input, it will overwrite each other.
- We do not need to use redis if uploading files is done in model-backend. Redis is only used for transferring data between model-backend and temporal workers
This commit
- remove redis.set in sync trigger handler
> fix(redis): fix input value overwrite

- go.mod
- go.sum
- pkg/ray/ray.go
Because
- When only "Scaling" is displayed, users don't know which specific status it refers to.
This commit
- add separate states for scaling
> feat(ray): add separate state for scaling

- go.mod
- go.sum
- pkg/datamodel/datamodel.go
- pkg/db/migration/000009_model_trigger.down.sql
- pkg/db/migration/000009_model_trigger.up.sql
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/worker/workflow.go
Because
- On the Explore page, all models are publicly available. Displaying the "Run" count will help new users who are unsure of what they need to start with the most popular models. One of the indicators for popularity is the number of times a model has been run.
- For users managing their own resources, it allows a quick understanding of the popularity of their models, whether public or private.
This commit
- support model statistics in model message
> feat(model): support model statistics in model message

- pkg/handler/public.go
Because
- When models are displayed on the Explore page, they are shown as long as they are set to "public," with no other conditions or restrictions. The Explore page aims to be attractive and meaningful to users. Therefore, it is important that models are only shared if the owner has run them successfully at least once before sharing with others.
This commit
- support `num_of_runs` in list filter
> feat(model): support num_of_runs in list filter

- pkg/handler/public.go
- pkg/repository/transpiler.go
Because
- filter field should be camelCase
This commit
- use camelCase for filter
> chore(filter): use camelCase for filter

- go.mod
- go.sum
- pkg/constant/constant.go
- pkg/datamodel/modeltrigger.go
- pkg/db/migration/000009_model_trigger.up.sql
- pkg/handler/operation.go
- pkg/handler/public.go
- pkg/handler/trigger.go
- pkg/mock/mock_repository.go
- pkg/ray/ray.go
- pkg/repository/repository.go
- pkg/resource/resource.go
- pkg/service/service.go
- pkg/service/worker.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- We now store each trigger I/O data in minio, we do not need to store/retrieve data from `redis` anymore
- FE now support triggering model with selected version
This commit
- replace I/O data retrieval from redis with minio
- support getting latest operation with particular model version
> feat(redis): replace I/O data retrieval from redis with minio

- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- Trigger activity retry will result in duplicate primary key for trigger record
This commit
- move createTrigger to workflow
> fix(workflow): fix duplicate key when activity retry

- pkg/handler/trigger.go
- pkg/ray/const.go
- pkg/ray/util.go
- pkg/service/const.go
- pkg/service/service.go
- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- We should allow model to be triggered in offline/start/scaling state
- We should only record trigger time when the model is deployed
This commit
- allow triggering in offline/start/scaling state
- check model state before processing actual request
> chore(trigger): allow triggering in offline/start/scaling state

- pkg/worker/workflow.go
Because
- wrong logical expression used when checking starting/scaling state
This commit
- fix state check
> fix(workflow): fix state check

- pkg/handler/private.go
- pkg/handler/public.go
- pkg/mock/mock_repository.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- Delete model will result in `version not found` error
- Delete model will left dangling version records in db
This commit
- fix delete version with residuals
> fix(version): fix delete version with residuals

- pkg/handler/trigger.go
- pkg/service/service.go
- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- current model run logs are created only in temporal workflow
This commit
- extend run log lifecycle
> refactor(run): extend run log scope

- pkg/handler/trigger.go
- pkg/service/service.go
- pkg/service/worker.go
- pkg/worker/workflow.go
Because
- When users are impersonating the same entity, they can see others input/output
This commit
- append both userUID and requesterUID in redis operation key to make it unique
> fix(redis): avoid possibility to see other's request and response

- pkg/service/service.go
Because
- run logs should show runner id
This commit
- fix runner missing issue
> fix(run): fix Runner missing issue

- pkg/service/service.go
- pkg/service/utils.go
Because
- list model run should return results even if there is an error in minio
This commit
- log errors instead of return error
> fix(run): not return minio error in list model run

- go.mod
- pkg/repository/transpiler.go
- pkg/service/convert.go
- pkg/service/service.go
Because
- We didn't apply any naming convention on tags
This commit
- Standardizes the tag naming convention to match the following criteria:
- All user-defined tags will be converted to lowercase.
- All system/reserved tags will be capitalized.
> feat(service): standardize the tag naming convention

- go.mod
- go.sum
- pkg/handler/mock_service_test.go
- pkg/handler/public.go
- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- pkg/service/service.go
Because
- console runs page needs to display requester
This commit
- expose requester id in model runs response
> feat(run): add requester id in list model run response

- cmd/main/main.go
- config/config.go
- pkg/service/metadataretention.go
- pkg/service/service.go
- pkg/service/service_test.go
Because
- expiry tag should be set by different environments
This commit
- add metadata retention handler
> fix(run): add metadata retention handler

- go.mod
- go.sum
- pkg/service/utils.go
Because
- dashboard needs pipeline/model namespace id to redirect
This commit
- add namespace id in response
> fix(run): add namespace id in response

- config/config.yaml
- pkg/db/migration/000011_run_logging_namespace.down.sql
- pkg/db/migration/000011_run_logging_namespace.up.sql
- pkg/db/migration/000012_migrate_unsupported_task.down copy.sql
- pkg/db/migration/000012_migrate_unsupported_task.up.sql
Because
- we have not support `TASK_IMAGE_TO_IMAGE` in the new AI Task standard
This commit
- migrate unsupported task to `TASK_CUSTOM
> fix(migration): migrate unsupported task to custom

- go.mod
- go.sum
- pkg/service/service.go
- pkg/service/utils.go
Because
- The `ModelRun` object has confusing documentation and field names for the requester, runner and owner of a model run.
This commit
- Implements changes in https://github.com/instill-ai/protobufs/pull/519.
> chore(run): clarify actors in ModelRun

- pkg/ray/util.go
Because
- wrong int parse
This commit
- fix regex match parse
> chore(utils): fix regex match parse

- pkg/ray/ray.go
Because
- ray model deployment is missing `ray_pb` module
This commit
- fix missing deployment configs and mounts
> fix(ray): fix missing deployment configs

- cmd/main/main.go
- cmd/worker/main.go
- go.mod
- go.sum
- pkg/service/metadataretention.go
- pkg/service/service.go
Because
- https://github.com/instill-ai/pipeline-backend/pull/937 modifies the
metadata retention interface, allowing clients to fetch both the
expiration tag and the duration.
This commit
- Align metadata retention implementation with `pipeline-backend`'s.
> chore(minio): align expiry rules with pipeline-backend

- cmd/main/main.go
- cmd/worker/main.go
- pkg/mock/ray_mock.gen.go
- pkg/ray/const.go
- pkg/ray/ray.go
Because
- avoid constant disk IO ops
This commit
- utilize redis as deployment config cache
- write config to persistent disk only on program exit
> feat(ray): utilize redis as deployment config cache

- .github/workflows/images.yml
Because
- Build [fails](https://github.com/instill-ai/model-backend/actions/runs/13271033782/job/37075787828) due to missing images to remove.
```sh
mkdir /tmp/test
df --human-readable
sudo apt clean
docker rmi $(docker image ls --all --quiet)
rm --recursive --force "$AGENT_TOOLSDIRECTORY"
df --human-readable
shell: /usr/bin/bash -e {0}
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        72G   45G   28G  63% /
tmpfs           7.9G   84K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb16      881M   59M  761M   8% /boot
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
WARNING: apt does not have a stable CLI …
```
> fix(ci): remove docker images only when they exist

- go.mod
- go.sum
Because
- Audit logs need to be emitted by MinIO in order to include actions from any client. Still, we need to identify who performed an action.
This commit
- Updates `x/minio` with changes in instill-ai/x#36
> feat(x): update MinIO package to delegate audit logs

- .github/workflows/images.yml
- .github/workflows/integration-test.yml
- Dockerfile
- cmd/main/main.go
- cmd/worker/main.go
- go.mod
- go.sum
Because
- We want to identify the service that is performing a MinIO action.
This commit
- Adds client information (app name and version) to the MinIO requests according to instill-ai/x/pull/37.
> feat(minio): add service name and version to MinIO requests

- .golangci.yaml
- config/config.yaml
- go.mod
- go.sum
- pkg/handler/create.go
- pkg/handler/public.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- MinIO config params lead to the conclusion that the root credentials are needed, when any valid user/pass with the right permissions (bucket & object) will be valid.
This commit
- Updates the configuration for the MinIO client.
> chore(minio): do not configure MinIO with root credentials

- cmd/main/main.go
- cmd/worker/main.go
- config/config.go
- go.mod
- go.sum
- pkg/service/metadataretention.go
- pkg/service/service.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
- pkg/worker/workflow.go
Because
- `x/minio` has been updated with some API breaking changes.
This commit
- Migrates to the latest `x/minio`.
> chore(minio): update x/minio package

- pkg/mock/ray_mock.gen.go
- pkg/ray/const.go
- pkg/ray/ray.go
- pkg/ray/util.go
- pkg/service/service.go
Because
- Ray is going to deprecate `runtime_env`'s `container` field on 31st July
This commit
- adopts `image_uri` as the alternative. 
- removes redundant scaling configuration logic.
> chore(ray): deprecate runtime_env container

- config/config.go
- config/config.yaml
- pkg/ray/ray.go
Because
- config for `model-store` volume mounting is overkilled and not used at all
This commit
- remove model store configuration
> chore(configs): remove model store config

- .github/workflows/images.yml
- .github/workflows/integration-test.yml
- Dockerfile
Because
- `github.sha` is the complete commit SHA hash which is too long. Shot commit hash is preferred, especially for the backend service log presentation.
This commit
- adopted short git commit hash for representing the `latest` build version
> ci(workflows): adopt short commit hash for service version

- cmd/migration/main.go
- config/config.go
- config/config.yaml
- pkg/db/db.go
Because
- The DB version should always be bound to the codebase; we shouldn’t use a config file for it.
This commit
- Removes the DB version from the config file.
> refactor(config): remove db version from config file

- cmd/worker/main.go
- config/config.yaml
- go.mod
- go.sum
Because
- The Temporal namespace will now be initialized when the Temporal service starts.
Ref: https://github.com/instill-ai/instill-core/pull/1352
- We now use the shared `instill-core` namespace across all services.
This commit
- Removes Temporal namespace initialization
- Adopts the latest `x/temporal` package to support API key authentication for connecting to Temporal Cloud
> feat(temporal): remove Temporal namespace initialization
